[package]
name = "aoc-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
criterion = "0.8.0"
minilp = "0.2"
itertools = "0.14.0"
rayon = "1.11.0"
regex = "1.12.2"

[[bench]]
name = "day07"
harness = false
